import type { Metadata } from "next";
import "./globals.css";
import { UIProvider } from "@ddalkakmall/ui";
import { LoadingBar } from "@cher1shrxd/loading";
import { colors } from "@ddalkakmall/ui/tokens";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <LoadingBar color={colors.text.DEFAULT} />
        <UIProvider>{children}</UIProvider>
      </body>
    </html>
  );
}
